version: "3.8"

services:
  mc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "1.18.2-40.2.9"
      MEMORY: "6G"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  data: {}